# Generated by Django 4.0.1 on 2022-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_discount_price', models.FloatField()),
                ('product_is_promoted', models.CharField(max_length=50)),
                ('sub_category_name', models.CharField(max_length=50, null=True)),
                ('sales_ch', models.CharField(max_length=70, null=True)),
                ('brand', models.TextField(max_length=50, null=True)),
                ('score', models.FloatField(null=True)),
            ],
        ),
    ]
