# Generated by Django 4.0.1 on 2022-08-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_products_city_names_products_seller_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='city_names',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sellers_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
