# Generated by Django 4.0.1 on 2022-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_products_city_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seller_scores',
            field=models.FloatField(max_length=500, null=True),
        ),
    ]
