# Generated by Django 4.0.1 on 2022-08-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_products_seller_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seller_scores',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
