# Generated by Django 4.0.1 on 2022-08-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_alter_products_seller_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trendyol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_discount_price', models.FloatField()),
                ('product_is_promoted', models.CharField(max_length=50)),
                ('sub_category_name', models.CharField(max_length=50, null=True)),
                ('sales_ch', models.CharField(max_length=70, null=True)),
                ('city', models.TextField(max_length=50, null=True)),
                ('score', models.FloatField(null=True)),
                ('sellers_name', models.CharField(max_length=500, null=True)),
                ('city_names', models.CharField(max_length=500, null=True)),
                ('seller_scores', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
